/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BenefitScheme {
  'name' : string,
  'salaryRangeMax' : bigint,
  'salaryRangeMin' : bigint,
  'eligibilityDepartment' : string,
  'eligibilityDesignation' : string,
  'benefitType' : string,
}
export interface EmployeeRecord {
  'status' : string,
  'salary' : bigint,
  'name' : string,
  'designation' : string,
  'date_of_joining' : string,
  'email' : string,
  'phone' : string,
  'department' : string,
  'location' : string,
  'employee_id' : string,
}
export interface ValidationRequest {
  'benefitSchemeName' : string,
  'employeeId' : string,
  'requestedAmount' : bigint,
  'timestamp' : bigint,
}
export interface ValidationResponse {
  'isEligible' : boolean,
  'message' : string,
  'approvedAmount' : bigint,
  'reason' : [] | [string],
}
export interface _SERVICE {
  'addBenefitScheme' : ActorMethod<[BenefitScheme], undefined>,
  'addEmployee' : ActorMethod<[EmployeeRecord], undefined>,
  'getBenefitScheme' : ActorMethod<[string], [] | [BenefitScheme]>,
  'getEmployee' : ActorMethod<[string], [] | [EmployeeRecord]>,
  'validateEligibility' : ActorMethod<[ValidationRequest], ValidationResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];