/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CitizenID = IDL.Text;

export const idlService = IDL.Service({
  'requestMoney' : IDL.Func([CitizenID], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CitizenID = IDL.Text;
  
  return IDL.Service({ 'requestMoney' : IDL.Func([CitizenID], [], []) });
};

export const init = ({ IDL }) => { return []; };